[package]
name = "kimchi_example"
version = "0.1.0"
edition = "2021"

[dependencies]
kimchi = { git = "https://github.com/o1-labs/proof-systems", branch="master"  }
ark-ff = { version = "0.3.0", features = ["parallel", "asm"] }

